### PR TITLE
Feature/storekit tests

### PR DESCRIPTION
**Pull request by gentique**
This PR is based on this comment https://github.com/poviolabs/PovioKit/pull/171#discussion_r908511815 

Though when I started developing, I noticed that you aren't able to create a `UIScene` by yourself, so I had to do some workarounds to get the desired behavior.

If you check the commits, you can see that I did some refactoring since I didn't like how some things turned out. I still think this can be done better, so I am very open to any suggestions!

### CODE REVIEW

**Review by ArlindDushi — APPROVED** [review]
LGTM 👌

**Comment by borut-t** [comment]
@gentique I really like your enthusiasm to cover this with unit tests. But from experience and from this example you can clearly see we need to put too much effort in order to test native functionalities. I would skip this tbh.

**Comment by gentique** [comment]
> @gentique I really like your enthusiasm to cover this with unit tests. But from experience and from this example you can clearly see we need to put too much effort in order to test native functionalities. I would skip this tbh.

It served me very well as an exercise since I haven't had a case where I needed to spy a type that you can't directly instantiate, therefore I'm perfectly fine with declining this PR.

**Comment by gentique** [comment]
@borut-t On a second note, it is not the native functionality I'm testing per se, rather this piece of logic `first { $0.activationState == .foregroundActive } as? UIWindowScene` , since I can't assert if SKStoreController presents the reviewRequest popup, nor if UIApplication gives us any scenes back.

**Comment by borut-t** [comment]
@gentique nice. We could save it maybe in the examples repo so we don't loose what you've worked on 🤷‍♂️

**Pull request closed without merging**
