### PR TITLE
Feature/XCConfigValue property wrapper

### PR DESCRIPTION
**Pull request by EgzonArifi**
* Property wrapper implementation for accessing build configuration values

### CODE REVIEW

**Review by gentique — APPROVED** [review]
LGTM,
I was thinking about adding tests, though that might require editing the workflow to attach a `.xcconfig`.

Thoughts @borut-t ?

**Review by yllfejziu — CHANGES_REQUESTED** [review]

**Review by borut-t — APPROVED** [review]
Great work. I like it 👌

**Comment by borut-t** [comment]
@gentique can you elaborate here a bit since you've recently worked with xcconfigs..

**Review by yllfejziu — APPROVED** [review]
👌

**Pull request merged**
